spring.application.name=ecom-stock
spring.main.web-application-type=reactive

db.url=ecom-stock-mysql-lb
db.port=33061

spring.r2dbc.url=r2dbc:mysql://${db.url}:${db.port}/stock
spring.r2dbc.username=ENC(a24EnxOWG3fMKyt16Wbrg/bfOFoDdfzqsyXr5IM0vnpz+MFc7BK3vkWzIiQrTJm3)
spring.r2dbc.password=ENC(3MKRbT6yuR7VoILXJriaLV4EpcEmQ/lA4OGuzEOHRGzeDYESCRT06lMMDnRyJX71PFkf6mJ0ISJjIDC/NEf4yA==)

spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://${db.url}:${db.port}/stock
spring.flyway.user=${spring.r2dbc.username}
spring.flyway.password=${spring.r2dbc.password}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

app.product-api.url=http://ecom-product-api-lb

jasypt.encryptor.password=${ENCRYPTION_KEY}
jasypt.encryptor.algorithm=PBEWithHMACSHA512AndAES_256
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.RandomIvGenerator
jasypt.encryptor.key-obtention-iterations=1000

springdoc.swagger-ui.path=/apispec.html
springdoc.swagger-ui.url=/apispec.yaml
springdoc.api-docs.enabled=true

spring.messages.encoding=UTF-8

token.jwt.secret=ENC(ZKEtksIvWa5qhpAWMBbAxOSAdE+c9NFd2kDTCfYYneEyXtK0+WtsfgXwL7MWwu7fI87VNHbAf5gZ8V8uF6G4BQ==)
